apiVersion: velero.io/v1
kind: Backup
metadata:
  name: foobackup
  labels:
    velero.io/storage-location: default
  namespace: openshift-adp
spec:
  hooks: {}
  includedNamespaces:
  - foo
  includeClusterResources: true
  storageLocation: dpa-sample-1
  ttl: 720h0m0s
