apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foopvc
  namespace: foo
spec:
  storageClassName: gp2-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

